const SCENE_IMAGES: Record<string, string[]> = {
  political: [
    "/scenes/political/a_procurator_of_saint_mark_s_1952.5.79.jpg",
    "/scenes/political/agostino_barbarigo_1957.8.1.jpg",
    "/scenes/political/alessandro_alberti_with_a_page_1952.5.80.jpg",
    "/scenes/political/allegorical_portrait_of_dante_1961.9.57.jpg",
    "/scenes/political/andrea_de_franceschi_1937.1.35.jpg",
    "/scenes/political/cardinal_pietro_bembo_1952.5.28.jpg",
    "/scenes/political/doge_alvise_mocenigo_and_family_before_the_madonna_and_child_1961.9.44.jpg",
    "/scenes/political/eleonora_di_toledo_1961.9.7.jpg",
    "/scenes/political/gian_federico_madruzzo_1960.6.27.jpg",
    "/scenes/political/irene_di_spilimbergo_1942.9.83.jpg",
    "/scenes/political/portrait_of_a_gentleman_1937.1.52.jpg",
    "/scenes/political/portrait_of_a_humanist_1961.9.38.jpg",
    "/scenes/political/portrait_of_a_nobleman_1942.16.1.jpg",
    "/scenes/political/portrait_of_diego_de_guevara_1937.1.46.jpg",
    "/scenes/political/ranuccio_farnese_1952.2.11.jpg",
    "/scenes/political/sir_brian_tuke_1937.1.65.jpg",
    "/scenes/political/a_prince_of_saxony_1947.6.1.jpg",
    "/scenes/political/edward_vi_as_a_child_1937.1.64.jpg",
    "/scenes/political/hans_roth_obverse_1947.6.4.a.jpg",
    "/scenes/political/portrait_of_a_lady_1937.1.37.jpg",
    "/scenes/political/portrait_of_a_lady_1952.6.1.jpg",
    "/scenes/political/portrait_of_a_man_1959.9.1.jpg",
    "/scenes/political/portrait_of_a_woman_1959.9.2.jpg",
    "/scenes/political/portrait_of_a_young_woman_1942.9.51.jpg",
    "/scenes/political/margaretha_boghe_1962.9.2.jpg",
    "/scenes/political/portrait_of_a_man_with_a_landscape_view_1943.7.10.jpg",
    "/scenes/political/prince_hercule-francois_duc_d_alencon_1961.9.55.jpg",
    "/scenes/political/margarethe_vohlin_obverse_1947.6.5.a.jpg",
  ],
  military: [
    "/scenes/military/saint_george_and_the_dragon_1952.5.76.jpg",
    "/scenes/military/the_rule_of_mars_right_panel_1952.5.31.c.jpg",
    "/scenes/military/the_trojans_repairing_their_ships_in_sicily_1939.1.250.jpg",
    "/scenes/military/cephalus_punished_at_the_hunt_1943.4.55.jpg",
    "/scenes/military/scenes_from_a_legend_1939.1.344.c.jpg",
    "/scenes/military/the_judgment_of_paris_1961.9.80.jpg",
    "/scenes/military/fantastic_landscape_with_figures_1952.4.1.jpg",
    "/scenes/military/christ_at_the_sea_of_galilee_1952.5.27.jpg",
    "/scenes/military/the_healing_of_the_paralytic_1943.7.7.jpg",
    "/scenes/military/the_miraculous_draught_of_fishes_1997.21.1.jpg",
    "/scenes/military/procris_and_the_unicorn_1943.4.60.jpg",
  ],
  economic: [
    "/scenes/economic/the_card_players_1961.9.27.jpg",
    "/scenes/economic/ill-matched_lovers_1971.55.1.jpg",
    "/scenes/economic/rebecca_at_the_well_1952.5.82.jpg",
    "/scenes/economic/a_concert_1997.57.2.jpg",
    "/scenes/economic/still_life_with_apples_pears_cucumbers_figs_plums_and_a_melon_2023.3.2.jpg",
    "/scenes/economic/the_rule_of_bacchus_left_panel_1952.5.31.a.jpg",
    "/scenes/economic/venus_with_a_mirror_1937.1.34.jpg",
    "/scenes/economic/the_nymph_of_the_spring_1957.12.1.jpg",
    "/scenes/economic/a_young_woman_and_her_little_boy_1942.9.6.jpg",
    "/scenes/economic/allegory_of_love_1939.1.259.jpg",
    "/scenes/economic/orpheus_1942.9.2.jpg",
    "/scenes/economic/four_seasons_in_one_head_2010.77.1.jpg",
    "/scenes/economic/_titian_s_schoolmaster_1942.9.45.jpg",
    "/scenes/economic/susanna_1939.1.231.jpg",
    "/scenes/economic/charity_1957.14.5.jpg",
    "/scenes/economic/cupid_with_the_wheel_of_time_1939.1.213.jpg",
    "/scenes/economic/venus_blindfolding_cupid_1952.2.12.jpg",
    "/scenes/economic/woman_holding_an_apple_1939.1.292.jpg",
    "/scenes/economic/a_lady_in_her_bath_1961.9.13.jpg",
  ],
  religious: [
    "/scenes/religious/the_nativity_1961.9.31.jpg",
    "/scenes/religious/the_annunciation_1959.9.6.jpg",
    "/scenes/religious/the_adoration_of_the_shepherds_1978.46.1.jpg",
    "/scenes/religious/the_baptism_of_christ_1942.9.5.jpg",
    "/scenes/religious/the_holy_family_with_angels_1943.4.28.jpg",
    "/scenes/religious/the_madonna_of_the_stars_1947.6.6.jpg",
    "/scenes/religious/madonna_adoring_the_child_1939.1.144.jpg",
    "/scenes/religious/saint_luke_2012.79.2.jpg",
    "/scenes/religious/saint_john_the_evangelist_on_patmos_1957.14.6.jpg",
    "/scenes/religious/the_flight_into_egypt_1937.1.28.jpg",
    "/scenes/religious/the_flight_into_egypt_1961.9.81.jpg",
    "/scenes/religious/christ_washing_the_disciples_feet_2001.29.1.jpg",
    "/scenes/religious/the_ecstasy_of_the_magdalen_2002.12.1.jpg",
    "/scenes/religious/the_magdalen_1961.9.56.jpg",
    "/scenes/religious/the_worship_of_the_golden_calf_1939.1.180.jpg",
    "/scenes/religious/saint_jerome_in_the_wilderness_1961.9.47.jpg",
    "/scenes/religious/madonna_and_child_and_the_infant_saint_john_in_a_landscape_1937.1.36.jpg",
    "/scenes/religious/madonna_and_child_with_saint_elizabeth_and_saint_john_the_baptist_1985.11.1.jpg",
    "/scenes/religious/a_gentleman_in_adoration_before_the_madonna_1939.1.114.jpg",
    "/scenes/religious/the_annunciation_to_the_shepherds_1939.1.126.jpg",
    "/scenes/religious/portrait_of_a_clergyman_johann_dorsch_1952.2.17.jpg",
    "/scenes/religious/saint_bernard_with_donor_obverse_1942.16.2.a.jpg",
    "/scenes/religious/saint_lucy_and_a_donor_1961.9.48.jpg",
    "/scenes/religious/saint_mary_cleophas_and_her_family_1961.9.88.jpg",
    "/scenes/religious/the_rest_on_the_flight_into_egypt_1961.9.36.jpg",
    "/scenes/religious/the_presentation_and_marriage_of_the_virgin_and_the_annunciation_1961.9.70.jpg",
  ],
  crisis: [
    "/scenes/crisis/the_crucifixion_with_the_converted_centurion_1961.9.69.jpg",
    "/scenes/crisis/the_martyrdom_of_saint_catherine_1952.2.18.jpg",
    "/scenes/crisis/the_martyrdom_and_last_communion_of_saint_lucy_1984.28.1.jpg",
    "/scenes/crisis/the_conversion_of_saint_paul_1961.9.43.jpg",
    "/scenes/crisis/the_despair_of_cephalus_1943.4.58.jpg",
    "/scenes/crisis/the_fall_of_man_middle_panel_1952.5.31.b.jpg",
    "/scenes/crisis/the_temptation_of_saint_anthony_1952.2.19.jpg",
    "/scenes/crisis/lamentation_1960.6.37.jpg",
    "/scenes/crisis/lamentation_1991.19.1.jpg",
    "/scenes/crisis/cephalus_hiding_the_jewels_1943.4.53.jpg",
    "/scenes/crisis/hans_roth_reverse_1947.6.4.b.jpg",
    "/scenes/crisis/saint_mary_salome_and_her_family_1961.9.89.jpg",
    "/scenes/crisis/margarethe_vohlin_reverse_1947.6.5.b.jpg",
    "/scenes/crisis/portrait_of_a_man_possibly_jan_snoeck_1967.4.1.jpg",
  ],
};

export function getSceneImage(category: string, scenarioId: string): string[] {
  const images = SCENE_IMAGES[category] || SCENE_IMAGES.political;
  const hash = scenarioId.split("").reduce((a, c) => a + c.charCodeAt(0), 0);
  const idx = hash % images.length;
  const idx2 = (hash + 7) % images.length;
  return idx === idx2 ? [images[idx]] : [images[idx], images[idx2]];
}
